-- first create user agenda:
-- CREATE USER AGENDA IDENTIFIED BY <yout_desired_password>;

-- then grant DBA role to agenda:
-- GRANT DBA TO AGENDA;

-- the run the tables creation:
/*
  In order to set the database charset to UTF-8 proceed as described below (more can be found here http://anuragkumarjoy.blogspot.ro/2013/09/how-to-change-character-set-in-oracle.html)
  SQL> shutdown immediate;
  // do a full backup of the database because the ALTER DATABASE CHARACTER SET statement cannot be rolled back.
  SQL> startup mount;
  SQL> ALTER SYSTEM ENABLE RESTRICTED SESSION;
  SQL> ALTER SYSTEM SET JOB_QUEUE_PROCESSES=0;
  SQL> ALTER SYSTEM SET AQ_TM_PROCESSES=0;
  SQL> ALTER DATABASE OPEN;
  SQL> ALTER DATABASE CHARACTER SET AL32UTF8;
  SQL> shutdown immediate;
  SQL> startup;
*/

CREATE TABLE "AGENDA"."REGIONS" (
  "ID" NUMBER(10,0) NOT NULL,
  "CODE" VARCHAR2(3) NOT NULL,
  "NAME" VARCHAR2(100) NOT NULL,
  PRIMARY KEY ("ID")
);

INSERT ALL
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (1, 'AB', 'Alba')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (2, 'AR', 'Arad')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (3, 'AG', 'Arges')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (4, 'BC', 'Bacau')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (5, 'BH', 'Bihor')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (6, 'BN', 'Bistrita-Nasaud')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (7, 'BT', 'Botosani')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (8, 'BR', 'Braila')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (9, 'BV', 'Brasov')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (10, 'B', 'Bucuresti')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (11, 'BZ', 'Buzau')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (12, 'CL', 'Calarasi')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (13, 'CS', 'Caras-Severin')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (14, 'CJ', 'Cluj')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (15, 'CT', 'Constanta')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (16, 'CV', 'Covasna')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (17, 'DB', 'Dambovita')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (18, 'DJ', 'Dolj')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (19, 'GL', 'Galati')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (20, 'GR', 'Giurgiu')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (21, 'GJ', 'Gorj')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (22, 'HG', 'Harghita')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (23, 'HD', 'Hunedoara')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (24, 'IL', 'Ialomita')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (25, 'IS', 'Iasi')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (26, 'IF', 'Ilfov')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (27, 'MM', 'Maramures')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (28, 'MH', 'Mehedinti')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (29, 'MS', 'Mures')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (30, 'NT', 'Neamt')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (31, 'OT', 'Olt')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (32, 'PH', 'Prahova')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (33, 'SJ', 'Salaj')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (34, 'SM', 'Satu Mare')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (35, 'SB', 'Sibiu')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (36, 'SV', 'Suceava')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (37, 'TR', 'Teleorman')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (38, 'TM', 'Timis')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (39, 'TL', 'Tulcea')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (40, 'VL', 'Valcea')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (41, 'VS', 'Vaslui')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (42, 'VN', 'Vrancea')
SELECT 1 FROM DUAL;
	
CREATE TABLE "AGENDA"."CONTACTS" (
	"ID" NUMBER(10,0) NOT NULL,
	"FIRSTNAME" VARCHAR2(100) NOT NULL, 
	"LASTNAME" VARCHAR2(100) NOT NULL, 
	"STREET" VARCHAR2(255) DEFAULT NULL, 
	"POSTALCODE" VARCHAR2(10) DEFAULT NULL, 
	"CITY" VARCHAR2(100) DEFAULT NULL, 
	"REGION_ID" NUMBER(10,0) DEFAULT NULL, 
	"PHONE" VARCHAR2(100) NOT NULL, 
	"EMAIL" VARCHAR2(120) DEFAULT NULL, 
	"IMG_PATH" VARCHAR2(255) DEFAULT NULL,
	PRIMARY KEY ("ID"),
	CONSTRAINT FK_CONTACTS_REGIONS FOREIGN KEY (REGION_ID) REFERENCES AGENDA.REGIONS (ID) ON DELETE SET NULL
);

--ALTER TABLE AGENDA.CONTACTS
--  ADD CONSTRAINT FK_CONTACTS_REGIONS FOREIGN KEY (AGENDA.REGION_ID) REFERENCES AGENDA.REGIONS (ID) ON DELETE SET NULL ON UPDATE CASCADE;

INSERT ALL
    INTO AGENDA.CONTACTS (ID,FIRSTNAME,LASTNAME,STREET,POSTALCODE,CITY,REGION_ID,PHONE,EMAIL,IMG_PATH) VALUES (2, 'Gerald', 'Cambrault', NULL, NULL, NULL, NULL, '0722222222', 'gerald.cambrault@agenda.dev', 'uploads/Mickey_Mouse.jpg')
    INTO AGENDA.CONTACTS (ID,FIRSTNAME,LASTNAME,STREET,POSTALCODE,CITY,REGION_ID,PHONE,EMAIL,IMG_PATH) VALUES (3, 'Cătălin', 'Ionescu', 'Str. Basarabiei, Nr. 100', NULL, 'Targoviste', 17, '0728186219', 'catalin.ionescu@agenda.dev', NULL)
    INTO AGENDA.CONTACTS (ID,FIRSTNAME,LASTNAME,STREET,POSTALCODE,CITY,REGION_ID,PHONE,EMAIL,IMG_PATH) VALUES (4, 'Ioana', 'Petrescu', 'Str. Bujorului, Nr. 6, Bl. 10, Sc. A', '10000', 'Bucuresti', 10, '0728186218', 'ioana.petrescu@agenda.dev', '')
    INTO AGENDA.CONTACTS (ID,FIRSTNAME,LASTNAME,STREET,POSTALCODE,CITY,REGION_ID,PHONE,EMAIL,IMG_PATH) VALUES (5, 'Costin', 'Corbu', 'Str. Test, #100', '123123', 'Alba-Iulia', 1, '0722111111111', 'costin.corbu@agenda.dev', NULL)
    INTO AGENDA.CONTACTS (ID,FIRSTNAME,LASTNAME,STREET,POSTALCODE,CITY,REGION_ID,PHONE,EMAIL,IMG_PATH) VALUES (6, 'Alin', 'Dobra', NULL, '', 'Bucuresti', 10, '+ 4 0123312321312', 'alin.dobra@agenda.dev', NULL)
    INTO AGENDA.CONTACTS (ID,FIRSTNAME,LASTNAME,STREET,POSTALCODE,CITY,REGION_ID,PHONE,EMAIL,IMG_PATH) VALUES (7, 'Teo', 'Willy', NULL, NULL, 'București', 10, '021321312312', NULL, NULL)
    INTO AGENDA.CONTACTS (ID,FIRSTNAME,LASTNAME,STREET,POSTALCODE,CITY,REGION_ID,PHONE,EMAIL,IMG_PATH) VALUES (8, 'John', 'Doe', 'Bld. Unirii', '987', 'Ploiești', 32, '074324323443', 'john.doe@example.com', NULL)
    INTO AGENDA.CONTACTS (ID,FIRSTNAME,LASTNAME,STREET,POSTALCODE,CITY,REGION_ID,PHONE,EMAIL,IMG_PATH) VALUES (9, 'Valentin', 'Cristian', 'Bld. Elisabeta, nr. 10003B', '13134', 'Bucuresti', 10, '072233333333', 'valentin.cristian@agenda.dev', NULL)
    INTO AGENDA.CONTACTS (ID,FIRSTNAME,LASTNAME,STREET,POSTALCODE,CITY,REGION_ID,PHONE,EMAIL,IMG_PATH) VALUES (10, 'Andreea', 'Alexandrescu', 'Str. abcdefg', NULL, NULL, NULL, '0345123123123', NULL, NULL)
    INTO AGENDA.CONTACTS (ID,FIRSTNAME,LASTNAME,STREET,POSTALCODE,CITY,REGION_ID,PHONE,EMAIL,IMG_PATH) VALUES (11, 'Stefan', 'Popescu', NULL, '100', 'Campina', 32, '0712321312312', 'stefan.popescu@example.com', NULL)
SELECT 1 FROM DUAL;

CREATE TABLE "AGENDA"."ADMIN" (
	"ID" NUMBER(10,0) NOT NULL,
	"USERNAME" VARCHAR2(100) NOT NULL, 
	"PASSWORD" VARCHAR2(100) NOT NULL, 
	PRIMARY KEY ("ID")
);

INSERT ALL
	INTO AGENDA.ADMIN (ID, USERNAME, PASSWORD) VALUES (1, 'admin', '123')
    INTO AGENDA.ADMIN (ID, USERNAME, PASSWORD) VALUES (2, 'bogdan', '123')
SELECT 1 FROM DUAL;