-- first create user agenda:
-- CREATE USER AGENDA IDENTIFIED BY <yout_desired_password>;

-- then grant DBA role to agenda:
-- GRANT DBA TO AGENDA;

-- the run the tables creation:

CREATE TABLE "AGENDA"."REGIONS" (
  "ID" NUMBER(10,0) NOT NULL,
  "CODE" VARCHAR2(3) NOT NULL,
  "NAME" VARCHAR2(100) NOT NULL,
  PRIMARY KEY ("ID")
);

INSERT ALL
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (1, 'AB', 'Alba')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (2, 'AR', 'Arad')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (3, 'AG', 'Arges')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (4, 'BC', 'Bacau')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (5, 'BH', 'Bihor')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (6, 'BN', 'Bistrita-Nasaud')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (7, 'BT', 'Botosani')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (8, 'BR', 'Braila')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (9, 'BV', 'Brasov')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (10, 'B', 'Bucuresti')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (11, 'BZ', 'Buzau')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (12, 'CL', 'Calarasi')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (13, 'CS', 'Caras-Severin')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (14, 'CJ', 'Cluj')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (15, 'CT', 'Constanta')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (16, 'CV', 'Covasna')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (17, 'DB', 'Dambovita')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (18, 'DJ', 'Dolj')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (19, 'GL', 'Galati')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (20, 'GR', 'Giurgiu')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (21, 'GJ', 'Gorj')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (22, 'HG', 'Harghita')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (23, 'HD', 'Hunedoara')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (24, 'IL', 'Ialomita')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (25, 'IS', 'Iasi')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (26, 'IF', 'Ilfov')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (27, 'MM', 'Maramures')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (28, 'MH', 'Mehedinti')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (29, 'MS', 'Mures')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (30, 'NT', 'Neamt')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (31, 'OT', 'Olt')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (32, 'PH', 'Prahova')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (33, 'SJ', 'Salaj')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (34, 'SM', 'Satu Mare')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (35, 'SB', 'Sibiu')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (36, 'SV', 'Suceava')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (37, 'TR', 'Teleorman')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (38, 'TM', 'Timis')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (39, 'TL', 'Tulcea')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (40, 'VL', 'Valcea')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (41, 'VS', 'Vaslui')
	INTO AGENDA.REGIONS (ID, CODE, NAME) VALUES (42, 'VN', 'Vrancea')
SELECT 1 FROM DUAL;
	
CREATE TABLE "AGENDA"."CONTACTS" (
	"ID" NUMBER(10,0) NOT NULL,
	"FIRSTNAME" VARCHAR2(100) NOT NULL, 
	"LASTNAME" VARCHAR2(100) NOT NULL, 
	"STREET" VARCHAR2(255) DEFAULT NULL, 
	"POSTALCODE" VARCHAR2(10) DEFAULT NULL, 
	"CITY" VARCHAR2(100) DEFAULT NULL, 
	"REGION_ID" NUMBER(10,0) DEFAULT NULL, 
	"PHONE" VARCHAR2(100) NOT NULL, 
	"EMAIL" VARCHAR2(120) DEFAULT NULL, 
	"IMG_PATH" VARCHAR2(255) DEFAULT NULL,
	PRIMARY KEY ("ID"),
	CONSTRAINT FK_CONTACTS_REGIONS FOREIGN KEY (REGION_ID) REFERENCES AGENDA.REGIONS (ID) ON DELETE SET NULL
);

--ALTER TABLE AGENDA.CONTACTS
--  ADD CONSTRAINT FK_CONTACTS_REGIONS FOREIGN KEY (AGENDA.REGION_ID) REFERENCES AGENDA.REGIONS (ID) ON DELETE SET NULL ON UPDATE CASCADE;

INSERT ALL
	INTO AGENDA.CONTACTS (ID,FIRSTNAME,LASTNAME,STREET,POSTALCODE,CITY,REGION_ID,PHONE,EMAIL,IMG_PATH) VALUES ('2','adela','Alexandrescu',null,null,null,null,'072222222','adela.alexandrescu@example.com',null)
    INTO AGENDA.CONTACTS (ID,FIRSTNAME,LASTNAME,STREET,POSTALCODE,CITY,REGION_ID,PHONE,EMAIL,IMG_PATH) VALUES ('3','Catalin','Ionescu','Str. Basarabiei, Nr. 100',null,'Targoviste','17','021123456789','catalin.ionescu@example.com',null)
    INTO AGENDA.CONTACTS (ID,FIRSTNAME,LASTNAME,STREET,POSTALCODE,CITY,REGION_ID,PHONE,EMAIL,IMG_PATH) VALUES ('4','Bogdan','Constantinescu','Str. Bujorului, Nr. 6, Bl. 10, Sc. A','10000','Bucuresti','10','0728186218','bog_con@yahoo.com','uploads/bogdan.constantinescu.jpg')
    INTO AGENDA.CONTACTS (ID,FIRSTNAME,LASTNAME,STREET,POSTALCODE,CITY,REGION_ID,PHONE,EMAIL,IMG_PATH) VALUES ('5','Vasile','Alexandrescu','Str. Galileo, nr. 5, bl. 14, sc. 2','123456','Ploiesti','32','04123432421','vas.alex@alexandrescu.com',null)
SELECT 1 FROM DUAL;
